version: "3.3"
services:
  node:
    image: "node:18.15.0"
    user: "node"
    working_dir: /home/node/app
#    environment:
#      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
